### ISSUE TITLE
Upstreaming fixes for newer kernel versions?

### ISSUE THREAD

**Issue by htfy96** [OlfillasOdikno/dxgkrnl-dkms#1]
Hi,

Thanks for your fix for recent versions. I'm the maintainer of https://aur.archlinux.org/packages/dxgkrnl-dkms-git/. Would you like to authorize porting your fix to the upstream AUR repo? I can also add you as a co-maintainer as well if you're willing to take care of the package.

**Comment by OlfillasOdikno** [comment]
Sure, that would be great, I just forked it to GitHub, because I never published anything on the AUR before and for a one time thing that hardly anyone uses, I figured out it would be easier this way for me.
